
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-controller-get-post","number":59,"title":"Arnav recommendation request controller get post","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/59"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-DCM-PUT","number":50,"title":"Tyler dcm put","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/50"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-DCM-DELETE","number":49,"title":"Tyler dcm delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/49"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-DCM1GET","number":48,"title":"Tyler dcm1 get","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/48"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"Anthony-MenuItemReviews-Table","number":45,"title":"AJ -- Create database table for MenuItemReviews","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/45"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-DCMGETandPOST","number":44,"title":"Tyler DCM GET and POST","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/44"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-DCMRequestTable","number":43,"title":"Menus Tables done - T. Yang","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-1/pull/43"}]
